### ISSUE TITLE
File conflicts when building projects in parallel on Jenkins

### ISSUE THREAD

**Issue by dsplaisted** [AArnott/Nerdbank.GitVersioning#164]
I'm getting errors in CI where the `SetCloudBuildVariables` task is failing to write the `jenkins_build_number.txt`, presumably because other projects are writing it at the same time.  Should [Jenkins.WriteVersionFile](https://github.com/AArnott/Nerdbank.GitVersioning/blob/56aa4240de3c8eed70d95a9cf6db5679f6ac441c/src/NerdBank.GitVersioning/CloudBuildServices/Jenkins.cs#L50) be updated to use the same retry logic that was added in https://github.com/AArnott/Nerdbank.GitVersioning/commit/aeba28550fd60c4539f0f5731d5ddd0c1e5c2284?

> C:\Users\dotnet-bot\.nuget\packages\nerdbank.gitversioning\2.1.7\build\Nerdbank.GitVersioning.targets(117,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'D:\j\w\innerloop_Win---268ca7be\jenkins_build_number.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Nerdbank.GitVersioning.CloudBuildServices.Jenkins.WriteVersionFile(String buildNumber)
   at Nerdbank.GitVersioning.CloudBuildServices.Jenkins.SetCloudBuildNumber(String buildNumber, TextWriter stdout, TextWriter stderr)
   at Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\j\w\innerloop_Win---268ca7be\src\Utilities.UnitTests\Microsoft.Build.Utilities.UnitTests.csproj]

**Comment by AArnott** [comment]
I solved this type of problem elsewhere in https://github.com/AArnott/Nerdbank.GitVersioning/commit/aeba28550fd60c4539f0f5731d5ddd0c1e5c2284

Would anyone care to apply this same retry method to this code?

**Comment by dsplaisted** [comment]
> Would anyone care to apply this same retry method to this code?

Yes, I can do this.

**Comment by AArnott** [comment]
Great. I expect you'll need to move my utility method to the main assembly.

**Comment by dsplaisted** [comment]
How do you feel about moving it to a shared folder and compiling it into each assembly?  That's the way I went, probably because I've been working in the MSBuild code base which does that a lot :-)

**Comment by AArnott** [comment]
I'm not a huge fan of shared files, but it's better than making the class public, so I think it's the right choice here.
