### ISSUE TITLE
GetBuildVersion fails with NotSupportedException when version is a simple number

### ISSUE THREAD

**Issue by the-ress** [AArnott/Nerdbank.GitVersioning#251]
GetBuildVersion fails with NotSupportedException when `version` is a simple number (e.g. "16") even when it's in an older commit.

**Expected result:**
When it's the latest commit, I'd expect an informative error message.
Otherwise there shouldn't be any errors.

**Actual result:**
```
The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
System.NotSupportedException: Specified method is not supported.
   at Nerdbank.GitVersioning.SemanticVersionJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\SemanticVersionJsonConverter.cs:line 30
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, TypeobjectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Nerdbank.GitVersioning.VersionFile.TryReadVersionJsonContent(String jsonContent) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\VersionFile.cs:line 314
   at Nerdbank.GitVersioning.VersionFile.GetVersion(Commit commit, String repoRelativeProjectDirectory) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\VersionFile.cs:line 72
   at Nerdbank.GitVersioning.GitExtensions.CommitMatchesMajorMinorVersion(Commitcommit, Version expectedVersion, String repoRelativeProjectDirectory) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 409
   at Nerdbank.GitVersioning.VersionOracle.<>c__DisplayClass101_0.<CalculateVersionHeight>b__0(Commit c) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\VersionOracle.cs:line 457
   at Nerdbank.GitVersioning.GitExtensions.GetCommitHeight(Commit commit, Dictionary`2 heights, Func`2 continueStepping) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 506
   at Nerdbank.GitVersioning.GitExtensions.<>c__DisplayClass25_0.<GetCommitHeight>b__0(Commit p) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 511
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at Nerdbank.GitVersioning.GitExtensions.GetCommitHeight(Commit commit, Dictionary`2 heights, Func`2 continueStepping) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 511
   at Nerdbank.GitVersioning.GitExtensions.<>c__DisplayClass25_0.<GetCommitHeight>b__0(Commit p) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 511
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at Nerdbank.GitVersioning.GitExtensions.GetCommitHeight(Commit commit, Dictionary`2 heights, Func`2 continueStepping) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 511
   at Nerdbank.GitVersioning.GitExtensions.GetHeight(Commit commit, Func`2 continueStepping) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\GitExtensions.cs:line 114
   at Nerdbank.GitVersioning.VersionOracle.CalculateVersionHeight(String relativeRepoProjectDirectory, Commit headCommit, VersionOptions committedVersion, VersionOptions workingVersion) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\VersionOracle.cs:line 457
   at Nerdbank.GitVersioning.VersionOracle..ctor(String projectDirectory, Repository repo, Commit head, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\VersionOracle.cs:line 86
   at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) in c:\Code\Nerdbank.GitVersioning\src\NerdBank.GitVersioning\VersionOracle.cs:line 40
   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
   at MSBuildExtensionTask.ContextAwareTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by AArnott** [comment]
This is by design. NB.GV walks git history to determine the "version height" which is a core part of how the automated versioning works.

You should rebase to scrub commits with mistakes in your version.json authoring. 

The only other alternative is to author a commit which entirely _removes_ `version.json` from your tree, then author a new commit that reintroduces it. Then *do not merge or squash* these commits back with the other faulty ones. You must push them as a single history line.

**Comment by the-ress** [comment]
Can the error message include this explanation and which commit id is causing it?
