### ISSUE TITLE
Conflict with Cake addin and Cake.Git

### ISSUE THREAD

**Issue by flcdrg** [AArnott/Nerdbank.GitVersioning#288]
Using Cake.GitVersioning 2.3.38 with Cake 0.32.1 I'm getting the following error:

```
Error(s) occurred when compiling build script:
(3333,12): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<LibGit2Sharp.Tag>' to 'System.Collections.Generic.List<LibGit2Sharp.Tag>'
```

**Comment by flcdrg** [comment]
Actually, a simple build.cake file works - so must be something else coming into play here..

```
#addin nuget:?package=Cake.GitVersioning&version=2.3.38

var target = Argument("target", "Default");

var gitVersion = GitVersioningGetVersion();

Task("Default")
  .Does(() =>
{
  Information("Hello World!" + gitVersion.ToString());
});

RunTarget(target);
```

**Comment by flcdrg** [comment]
Ok.. I think it's a conflict with Cake.Git. This reproduces the problem:

```
#addin nuget:?package=Cake.Git&version=0.19.0
#addin nuget:?package=Cake.GitVersioning&version=2.3.38

var target = Argument("target", "Default");

var gitVersion = GitVersioningGetVersion();

Task("Default")
  .Does(() =>
{
  Information("Hello World!" + gitVersion.ToString());
});

RunTarget(target);
```

**Comment by AArnott** [comment]
Consolidating versions can be done via binding redirect, but I don't know if Cake has a feature to let that happen.

But loading two versions should actually work fine, provided that the two libgit2sharp assemblies never need to communicate. What is the callstack for the failure? We need to determine who is dealing with a `Tag` object obtained from one libgit2sharp version and trying to assign it to the other version.

**Comment by flcdrg** [comment]
Here's the diagnostic log from Cake.. Not much of a stack trace I'm afraid..

```
Module directory does not exist.
NuGet.config not found.
Analyzing build script...
Analyzing C:/tmp/CakeGvTest/build.cake...
Processing build script...
Installing addins...
Found package 'Cake.GitVersioning 2.3.34' in 'C:/tmp/CakeGvTest/tools/Addins'.
Package Cake.GitVersioning.2.3.34 has already been installed.
Successfully installed 'Cake.GitVersioning 2.3.34' to C:/tmp/CakeGvTest/tools/Addins
Executing nuget actions took 64.63 ms
The addin Cake.GitVersioning will reference Cake.GitVersioning.dll.
The addin Cake.GitVersioning will reference LibGit2Sharp.dll.
The addin Cake.GitVersioning will reference Microsoft.DotNet.PlatformAbstractions.dll.
The addin Cake.GitVersioning will reference NerdBank.GitVersioning.dll.
The addin Cake.GitVersioning will reference Newtonsoft.Json.dll.
The addin Cake.GitVersioning will reference System.Runtime.InteropServices.RuntimeInformation.dll.
The addin Cake.GitVersioning will reference Validation.dll.
Found package 'Cake.Git 0.19.0' in 'C:/tmp/CakeGvTest/tools/Addins'.
Package Cake.Git.0.19.0 has already been installed.
Successfully installed 'Cake.Git 0.19.0' to C:/tmp/CakeGvTest/tools/Addins
Executing nuget actions took 1.89 ms
The addin Cake.Git will reference Cake.Git.dll.
The addin Cake.Git will reference LibGit2Sharp.dll.
Verifying assembly 'Cake.GitVersioning, Version=2.3.34.8655, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333'.
Verifying assembly 'Microsoft.DotNet.PlatformAbstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Verifying assembly 'NerdBank.GitVersioning, Version=2.3.34.8655, Culture=neutral, PublicKeyToken=a4e8f1e6cbfd650b'.
Verifying assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
Verifying assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Verifying assembly 'Validation, Version=2.4.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7'.
Verifying assembly 'Cake.Git, Version=0.19.0.0, Culture=neutral, PublicKeyToken=null'.
Verifying assembly 'LibGit2Sharp, Version=0.25.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333'.
Adding assembly reference to mscorlib.dll...
Adding assembly reference to System.Core.dll...
Adding assembly reference to Cake.Core.dll...
Adding assembly reference to Cake.Common.dll...
Adding assembly reference to Cake.exe...
Adding assembly reference to System.dll...
Adding assembly reference to System.Xml.dll...
Adding assembly reference to System.Xml.Linq.dll...
Adding assembly reference to System.Data.dll...
Adding assembly reference to System.Runtime.dll...
Adding assembly reference to System.Collections.dll...
Adding assembly reference to netstandard.dll...
Adding assembly reference to Cake.GitVersioning.dll...
Adding assembly reference to LibGit2Sharp.dll...
Adding assembly reference to Microsoft.DotNet.PlatformAbstractions.dll...
Adding assembly reference to NerdBank.GitVersioning.dll...
Adding assembly reference to Newtonsoft.Json.dll...
Adding assembly reference to System.Runtime.InteropServices.RuntimeInformation.dll...
Adding assembly reference to Validation.dll...
Adding assembly reference to Cake.Git.dll...
Adding assembly reference to LibGit2Sharp.dll...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Build.AppVeyor...
Importing namespace Cake.Common.Build.AppVeyor.Data...
Importing namespace Cake.Common.Build.Bamboo...
Importing namespace Cake.Common.Build.Bamboo.Data...
Importing namespace Cake.Common.Build.BitbucketPipelines...
Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
Importing namespace Cake.Common.Build.Bitrise...
Importing namespace Cake.Common.Build.Bitrise.Data...
Importing namespace Cake.Common.Build.ContinuaCI...
Importing namespace Cake.Common.Build.ContinuaCI.Data...
Importing namespace Cake.Common.Build.GitLabCI...
Importing namespace Cake.Common.Build.GitLabCI.Data...
Importing namespace Cake.Common.Build.GoCD...
Importing namespace Cake.Common.Build.GoCD.Data...
Importing namespace Cake.Common.Build.Jenkins...
Importing namespace Cake.Common.Build.Jenkins.Data...
Importing namespace Cake.Common.Build.MyGet...
Importing namespace Cake.Common.Build.TeamCity...
Importing namespace Cake.Common.Build.TFBuild...
Importing namespace Cake.Common.Build.TFBuild.Data...
Importing namespace Cake.Common.Build.TravisCI...
Importing namespace Cake.Common.Build.TravisCI.Data...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Download...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.New...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Uninstall...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DotCover...
Importing namespace Cake.Common.Tools.DotCover.Analyse...
Importing namespace Cake.Common.Tools.DotCover.Cover...
Importing namespace Cake.Common.Tools.DotCover.Merge...
Importing namespace Cake.Common.Tools.DotCover.Report...
Importing namespace Cake.Common.Tools.DotNetCore...
Importing namespace Cake.Common.Tools.DotNetCore.Build...
Importing namespace Cake.Common.Tools.DotNetCore.BuildServer...
Importing namespace Cake.Common.Tools.DotNetCore.Clean...
Importing namespace Cake.Common.Tools.DotNetCore.Execute...
Importing namespace Cake.Common.Tools.DotNetCore.MSBuild...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Delete...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Push...
Importing namespace Cake.Common.Tools.DotNetCore.Pack...
Importing namespace Cake.Common.Tools.DotNetCore.Publish...
Importing namespace Cake.Common.Tools.DotNetCore.Restore...
Importing namespace Cake.Common.Tools.DotNetCore.Run...
Importing namespace Cake.Common.Tools.DotNetCore.Test...
Importing namespace Cake.Common.Tools.DotNetCore.Tool...
Importing namespace Cake.Common.Tools.DotNetCore.VSTest...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitLink...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Label...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InnoSetup...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSpec...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Add...
Importing namespace Cake.Common.Tools.NuGet.Init...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.List...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.VSWhere...
Importing namespace Cake.Common.Tools.VSWhere.All...
Importing namespace Cake.Common.Tools.VSWhere.Latest...
Importing namespace Cake.Common.Tools.VSWhere.Legacy...
Importing namespace Cake.Common.Tools.VSWhere.Product...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace Cake.Git...
Importing namespace Cake.GitVersioning...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...
Cake.exe : (2897,12): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<LibGit2Sharp.Tag>' 
to 'System.Collections.Generic.List<LibGit2Sharp.Tag>'
At C:\tmp\CakeGvTest\build.ps1:241 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ((2897,12): erro...Git2Sharp.Tag>':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: 
Cake.Core.CakeException: Error(s) occurred when compiling build script:
(2897,12): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<LibGit2Sharp.Tag>' to 
'System.Collections.Generic.List<LibGit2Sharp.Tag>'
   at Cake.Scriptin
g.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by AArnott** [comment]
Oh, cake is compiling C#, and evidently adding references for the transitive closure of dependencies to that compilation. I wonder what source code it's emitting that uses the Tag type.

Anyway, the only way to make that work is to use reference aliasing and then fully qualify every type including the reference alias where necessary. Probably a sizeable work item within the cake repo.

**Comment by AArnott** [comment]
It might help if you can get the source code that can't compile. Running this under the debugger and breaking on first chance exceptions may give you an opportunity to intercept and extract the source code.

**Comment by flcdrg** [comment]
Debugging Cake.exe under Visual Studio and stepping through the code, I can see the Location (from the Roslyn compilation diagnostics collection) for this is set as:

SourceLocation(@2897:12)"Cake.Git.GitAliases.GitTags(Context, repositoryDirectoryPath)"

So I think this must be something to do with script that Cake generates which is then combined with my .cake file

**Comment by flcdrg** [comment]
I've raised the question in the Cake Gitter room (https://gitter.im/cake-build/cake) . Will wait to hear back.

I agree NB.GV is not at fault. Whether there'll need to be changes made here (assuming Cake is updated to allow different assemblies to be referenced) remains to be seen.

**Comment by flcdrg** [comment]
Suggestion is to get Cake.Git upgraded to use the same version of LibGit2Sharp. I'll see if I can get that happening.

**Comment by AArnott** [comment]
That will stop the bleeding, but only till either cake plugin changes their libgit2sharp version again. NB.GV tends to upgrade this dependency whenever doing so will add support for another platform. I *think* that has mostly stabilized but I can't predict when the next upgrade will be.
