### ISSUE TITLE
LibGit2Sharp not working on sdk:2.2.105-alpine3.9

### ISSUE THREAD

**Issue by ctaggart** [AArnott/Nerdbank.GitVersioning#314]
Steps to reproduce:
```
docker run --rm -it mcr.microsoft.com/dotnet/core/sdk:2.2.105-alpine3.9 sh
dotnet tool install -g nbgv
$HOME/.dotnet/tools/nbgv get-version
```

Error:
```
/ # $HOME/.dotnet/tools/nbgv get-version

Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-a904fc6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-a904fc6: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String projectPath, String format, String singleVariable, String versionOrRef) in D:\a\1\s\src\nbgv\Program.cs:line 261
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in D:\a\1\s\src\nbgv\Program.cs:line 131
Aborted
```

**Comment by ctaggart** [comment]
Works fine with `sdk:2.2.105-alpine3.8`.

**Comment by ctaggart** [comment]
Hoping this is fixed by #316

**Comment by ctaggart** [comment]
This does not appear to have been fixed by #316 😢 . Here is how I tested locally:
```
docker run -it --rm -v ${PWD}:/src -w /src mcr.microsoft.com/dotnet/core/sdk:2.2.105-alpine3.9 sh
dotnet tool install -g nbgv --add-source bin/nbgv/Debug --version 2.3.144-gfd73cbad91
$HOME/.dotnet/tools/nbgv get-version
```

But still get:
```
/src # $HOME/.dotnet/tools/nbgv get-version

Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-a904fc6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-a904fc6: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String projectPath, String format, String singleVariable, String versionOrRef) in C:\Users\taggac\github\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 266
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in C:\Users\taggac\github\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 131
Aborted
```

**Comment by ctaggart** [comment]
It looks like the alpine-x64 libgit2 lib has a dependency on openssl 1.0, which alpine 3.8 has, but alpine 3.9 updated to 1.1.

binary dependencies:
```
apk add --update binutils
/src # readelf --all /root/.dotnet/tools/.store/nbgv/2.3.144-gfd73cbad91/nbgv/2.3.144-gfd73cbad91/tools/netcoreapp2.1/any/runtimes/alpine-x64/native/libgit2-a904fc6.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libssl.so.1.0.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.0.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.musl-x86_64.so.1]
```

https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.8
openssl 1.0.2r-r0

https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.9
openssl 1.1.1b-r1

@bording, any chance we can get native libgit2 binaries that separate out the two?

**Comment by bording** [comment]
:cry: 

Yeah, looks like we'll need new binaries as long as we've got the OpenSSL dependency. So many headaches because of that. At least we were able to get rid of curl.

**Comment by ctaggart** [comment]
I was surprised by the openssl dependency with curl gone. It would be amazing if the openssl dependency could be removed too.

**Comment by bording** [comment]
The problem is that libgit2 requires it to be able to talk to https remotes. The only way we'd realistically be able to drop it from LibGit2Sharp would be to compile libgit2 without https support, and then implement the support in managed code instead using the hooks libgit2 has for custom transports. There are concerns that it would be noticeably slower, though.

Doing that would drastically simplify the native binaries story though. At that point the only real dependency we'd be impacted by is what libc a distro uses.

**Comment by bording** [comment]
Give LibGit2Sharp 0.27.0-preview-0007 a try. The native binaries package it references includes an `alpine.3.9-x64` binary.
