### ISSUE TITLE
build.ps1 fails if solution location contains a space

### ISSUE THREAD

**Issue by asherber** [AArnott/Nerdbank.GitVersioning#99]
My solution dir is at `p:\visual studio\nerdbank.gitversioning`. Build.ps1 eventually fails with:
```
[13:33:48] Starting 'setPackageVersion'...
[13:33:53] 'setPackageVersion' errored after 4.63 s
[13:33:53] Error: Command failed: powershell -ExecutionPolicy Bypass -Command (P:\visual studio\nerdbank.gitversioning\s
rc\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1 -ProjectDirectory ".")
P:\visual : The term 'P:\visual' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ (P:\visual studio\nerdbank.gitversioning\src\nerdbank-gitversioning.n ...
+  ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (P:\visual:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
I moved my solution dir up a level, and everything builds fine.

**Comment by AArnott** [comment]
Thanks for this report. It looks like this would NPM impact end users as well.
